### ISSUE TITLE
Add a settings panel

### ISSUE THREAD

**Issue by ziobastardo** [frakbot/FWeather#1]
Hi, a setting panel will be welcome.

**Comment by rock3r** [comment]
Ok, exactly which setting you think could actually be useful? Keep in mind that I'm not planning to add any more information to the widget than it has already.

**Comment by ziobastardo** [comment]
Well, i think it's useful city selection (using current position or picked from a list) and refresh time for update.

**Comment by rock3r** [comment]
I guess that makes sense :) I'm not really sure about the city picking, thou. The widget is meant to be used to only work with the current location, as it wouldn't make much sense otherwise.

**Comment by rock3r** [comment]
In release 1.1 I will add a simple settings screen. See #5.

**Comment by ziobastardo** [comment]
Very good, thanks!
Il giorno 03/lug/2013 14:08, "Sebastiano" notifications@github.com ha
scritto:

**Comment by rock3r** [comment]
Closing it as settings panel has been added as of ceab4ee. Will be out in 1.1 soon.
