### ISSUE TITLE
Add Analytics

### ISSUE THREAD

**Issue by rock3r** [frakbot/FWeather#10]
This requires an opt-out in the settings screen as well.

**Comment by rock3r** [comment]
The Settings UI for this is already in place, starting from ce40c05.

**Comment by frapontillo** [comment]
What should we track here?

**Comment by rock3r** [comment]
I'd go for just some basic stuff, such as Activity launches and
customization usages.

**Comment by frapontillo** [comment]
Done, I'm closing this right after 5 is, so I can correctly test the behavior as a whole.
