### ISSUE TITLE
Create a proper licenses HTML and generator

### ISSUE THREAD

**Issue by rock3r** [frakbot/FWeather#11]
Just like in the other project ;)

**Comment by frapontillo** [comment]
I'll consider setting up a Grunt file that'll take care of building the license file. Stay tuned.

**Comment by rock3r** [comment]
:heart:

**Comment by frapontillo** [comment]
What libraries should I add to the license file?

**Comment by rock3r** [comment]
As of now, the two that are already in it, plus the Android-switch-backport
which I just added on branch 5.

**Comment by rock3r** [comment]
Postponed to release 1.3 hoping you get your PC by then :D

**Comment by rock3r** [comment]
Ok, it's pointless. You'll just do this once you actually manage to get a computer, @frapontillo . Which, I hope, happens SOON.
