### ISSUE TITLE
Randomize insulting messages for same event

### ISSUE THREAD

**Issue by frapontillo** [frakbot/FWeather#17]
Add a method that pseudo-randomly selects an insulting message for a certain event. 
For example, when sunny, we can have:
- There's some fucking love in the air.
- Just go to the fucking beach.
- For fuck's sake, get some ice.

**Comment by rock3r** [comment]
Postponed to a release TBD

**Comment by rock3r** [comment]
Took charge of this since @frapontillo isn't able to code ATM. Scheduled for v3.0.

**Comment by frapontillo** [comment]
This will need some improvements for the string selection phase, it is unmanageable as of now. xD

**Comment by frapontillo** [comment]
This should be completed, please check if everything is ok so I can merge into `develop`.
