### ISSUE TITLE
Add opaque background

### ISSUE THREAD

**Issue by frapontillo** [frakbot/FWeather#19]
Add a opaque background with transparency settings, just like DashClock.

**Comment by rock3r** [comment]
I already considered it and decided not to have it, we have the dark mode for that purpose.

**Comment by frapontillo** [comment]
This feature has been requested and makes a lot of sense when the background is a photograph.

**Comment by rock3r** [comment]
Postponed to release 1.3

**Comment by rock3r** [comment]
Closed as of 634569b

Also, release 1.3.0 has in the meantime been renamed to 2.0 because it's a big change
