### ISSUE TITLE
DashClock integration

### ISSUE THREAD

**Issue by frapontillo** [frakbot/FWeather#21]
It'd be nice to implement a DashClock extension, maybe with a popup with the full weather description in it.

It's already been requested by a user.

Elaborate.

**Comment by rock3r** [comment]
Will most likely be done (if it will ever be) after we have a details view.
Not sold on it thou.

**Comment by rock3r** [comment]
I'd add: I sure as hell am not really seeing a use case where a pop up shows upon cliking the DashClock extension's item. Also, when DashClock is minimized, there's just no point on having FWeather showing up on it. It'd just have the ability to show an icon and like 2-3 characters. That's not useful at all.

PS: the details view is #16 
PPS: we're not blindingly going to add whatever the users ask for, it has to make some kind of sense.

**Comment by frapontillo** [comment]
I'd like to see that too, thou.
Maybe just some short sentence like: "fucking raining", or "shitty thunders".

My 2 cents.

**Comment by rock3r** [comment]
Even if that actually could fit on the large DashClock layout (the list-based one), it'd be useful as fuck on the small DashClock layout. I insist, it's pretty useless. Also, this use case is pretty silly: a widget inside of a widget? Seriously? :dash:

**Comment by rock3r** [comment]
I mistakenly closed this instead of #20. Sorry. I'm tired.

**Comment by frapontillo** [comment]
Dumped, doesn't match the target.
