### ISSUE TITLE
Aggiungere opzioni

### ISSUE THREAD

**Issue by Torre10** [frakbot/FWeather#3]
Sarebbe bello se ci fosse un pannello per le impostazioni e all'interno la possibilità di scegliere ogni quanto aggiornare il widget, scegliere la località nel caso il widget non riuscisse a trovare il luogo corretto e la possibilità di modificare le frasi predefinite che si visualizzano sul widget perchè alcune sono ripetitive e monotone

**Comment by rock3r** [comment]
Duplicato di #1.

Arriverà, comunque, anche se non tutto assieme :+1:
