### ISSUE TITLE
Reduce fonts size for crappy devices

### ISSUE THREAD

**Issue by rock3r** [frakbot/FWeather#35]
Those fucking crappy devices have fuckingly small screens and insanely low display densities; text can't fit the space that launchers give to the widget, and thus we need to reduce text size by 20-30% on ldpi and mdpi phones in order to fit the motherfucking text in the shitty space.

**Comment by clonednull** [comment]
thats a motherfucking pitty mate, great you fixed it, now they can read the whole fucking text! ;-)

**Comment by frapontillo** [comment]
He didn't fix shit, he just opened a crappy useless issue.

**Comment by clonednull** [comment]
fuck, youre right man, i shouldnt read github when i'm drunk mate...
anyway no issue is useless when noticed for someone, i love this app so keep it alive!

**Comment by rock3r** [comment]
Thanks dude, envying your drunkness right now! Will force my lazy ass to
get this crap done as soon as I get some fucking time for it!

**Comment by rock3r** [comment]
Turns out it wasn't really closed. FUCK ME.
