### ISSUE TITLE
Add Temperature Value to Temperature Info Text

### ISSUE THREAD

**Issue by clonednull** [frakbot/FWeather#36]
Lo mates!
This isnt an "Issue" (as it would be an "Enhancement") but i really dont know where to post it so i post it here.
I know the Temperature Info Text should be enough fucking info for the current weather but for the precise ones i thought about adding the exact temperature value to the text.
For more details check out my added screenshots.
I have coded the fucking thing down so if you want i can share it with the Project.

![screenshot_2013-08-06-00-59-11](https://f.cloud.github.com/assets/5016480/913931/d4e2a652-fe26-11e2-9984-c5d1f21c4e5e.jpg)
![screenshot_2013-08-06-01-01-06](https://f.cloud.github.com/assets/5016480/913933/df4f598c-fe26-11e2-924e-d18e144b586b.jpg)

**Comment by rock3r** [comment]
Hey mate, that's brilliant!
I'm not fucking sold on the need to see the crappy temperature thou. There are a few fucking issues to solve.

First, some fucking lazyass countries never moved to the bloody Fahrenheit scale to the ruddy Celsius one, and that would require having the user choose the motherfucking scale they want to use. I'm afraid that would be a bit too fucking much to add to the already crowded motherfucking settings screen.

Second, and this is a fucking hipster design issue, I don't really see this widget as actually providing any fucking useful information. It's all about trash-talk and giving out crappy info that our idiot users could gather by simply looking out of a fucking window. This was the original concept as well.

If you want to post a fucking pull request anyway, we'll evaluate it to decide whether we want it in our crappy app (by rolling a fucking dice, most likely :D).

Thanks!

**Comment by clonednull** [comment]
Lo mate!

Well i think you're right mate. This app gives fucking more Information about the wehater then any other app but well i just wanted to get rid of the "other" fucking weather widgets, where only the "real" temperature is what i really wanted to know..
anyway thanks for fucking reading and drunken greetings!

ps:
i can fuck the Project anyway!!! ehm, sorry i meant fork the Project :)

**Comment by rock3r** [comment]
Indeed, you can :) cheers mate
