### ISSUE TITLE
The fucking text is too fucking small for fuck's sake!

### ISSUE THREAD

**Issue by defkev** [frakbot/FWeather#37]
No honestly, at 720x1280 the paragraph is on a single line and incredible hard to read even through the widget takes up 3x4 of the screen.

**Comment by rock3r** [comment]
I'd really appreciate a fucking screenshot and a few details on your phone
because I'm using a mothering 720p phone myself and the text size is
fucking perfect...

**Comment by defkev** [comment]
Oh i am so fucking sorry for forgetting the obvious...

![screenshot_2013-08-20-19-44-30](https://f.cloud.github.com/assets/5265345/995802/2c7b7468-09c4-11e3-9c1e-51916232405c.png)

Device: Samsung GNex (as in Galaxy Nexus)
ROM: MIUI V5 (Version 3.8.16)
Launcher: MIUI Home
Gridsize: 5x4

Screenshot shows the Widget in 3x4

Even if i put it on a new/blank view and resize it to 5x4 it still looks bloody disgusting.

Thanks in flying-fucking-muffin advanced!

**Comment by rock3r** [comment]
What the bloody fucking fuck! I can't really understand what the fuck is happening there. Or, I do have an idea, but if that's the case, there's nothing I can do about it.

My suspicion is that MIUI's launcher has very little cells (and this is kinda proven by the fact that there is a clusterfuck with those cramped icons there) and messes up big time with the spacing. This is how it looks in 4x3 on any device I've tested the widget on (including GNex on stock and Apex launcher): https://hostr.co/file/j0AIBZDGdzqA/2013-08-22-18.19.34.png

The widget has three "breakpoints" for the layout, which are small, medium and large. On 4x3 on a 720p device, it should end up in the large layout, and it does on each device I've tested it on (including tablets and 1080p phones). In your case, there isn't enough space to fit the large layout, so it has to switch to the medium one, which has smaller text and images, to be able to fit everything.

The breakpoints are hardcoded based on my experience and testing, and there's no way to provide dynamic sizing based on the available sizing, so the small/medium/large sizes with fixed breakpoints are the only mechanism we can count on.

If you resize the widget to, say, 4x4, does it increase its text and image sizes? Or not? I think the MIUI Launcher on the GNex falls in the blind spot of the breakpoints, causing it to be always on the "too small" side. Unfortunately there's nothing much I can do, if that's the case, without breaking things for everybody else.

Just out of curiosity, can you change the number of rows on the launcher and see what happens, or try another launcher? That could also be a bug in MIUI's launcher that reports the wrong size to the widget.

**Comment by rock3r** [comment]
Or, now that I think about it, the MIUI launcher could be trying to cheat by reporting the wrong density, to fit more stuff on the screen. That could be an issue as well.

**Comment by rock3r** [comment]
This issue is going to be closed soon if no one answers to the open points.

**Comment by rock3r** [comment]
Ok, I'm closing this. v2.0 has been released an no further report nor answer came in a month...
