### ISSUE TITLE
Use Fused Location Provider whenever possible

### ISSUE THREAD

**Issue by rock3r** [frakbot/FWeather#4]
As of release-1.0, the app uses some simple location handling logic.

Switching to Google Play Services' [Fused Location Provider](https://developer.android.com/google/play-services/location.html) should help get better positioning and save some battery as well.

**Comment by frapontillo** [comment]
I already did this [at the Android University Hackaton](https://github.com/frapontillo/city-tracker-2013/blob/master/src/it/auh/citytracker/activity/MainActivity.java) so I'm going to nail it.

**Comment by rock3r** [comment]
Be my guest :)
