### ISSUE TITLE
High network usage with "never" data sync interval

### ISSUE THREAD

**Issue by rock3r** [frakbot/FWeather#54]
Reported by user, who saw up to 15 MB data DLs in 15 minutes. Only happens when data syncing interval is set to "never".

**Comment by frapontillo** [comment]
No lolcat?

**Comment by rock3r** [comment]
Nope, the user is likely not rooted and on Android 4.1 or 4.2 (HTC One X+).

**Comment by rock3r** [comment]
Should have been fixed, according to the original reporter.
