### ISSUE TITLE
Add Pebble notifications

### ISSUE THREAD

**Issue by rock3r** [frakbot/FWeather#56]
Add an option to enable sending notifications to the Pebble smartwatch.

See [PebbleKit Android documentation](http://developer.getpebble.com/1/03_API_Reference/03_Android/#notifications).

**Comment by rkiesler** [comment]
I second that, I also have a Pebble and would be happy beta-testing that.

**Comment by frapontillo** [comment]
Now what.

**Comment by rock3r** [comment]
#fuckthis
