### ISSUE TITLE
No weather when offline 

### ISSUE THREAD

**Issue by rock3r** [frakbot/FWeather#59]
User reports: "as soon as I disconnect wi-fi, it gives the "look outside the windows" message which is really annoying!!"

**Comment by frapontillo** [comment]
It may be because there's some connection listener responding badly to connection changes.

**Comment by rock3r** [comment]
Probably. It's your code, could you please point me towards something to
look at? Or even better, fix it yourself? XD

**Comment by frapontillo** [comment]
Should be something around [here](https://github.com/frakbot/FWeather/blob/develop/src/net/frakbot/FWeather/receiver/ConnectivityBroadcastReceiver.java#L61), even though the code looks fine to me.
