### ISSUE TITLE
Where are conditions of weather parsed?

### ISSUE THREAD

**Issue by jw-mcgrath** [frakbot/FWeather#66]
I can't seem to find where you parse the information you get from the yahoo client to determine which xml string to display.

**Comment by frapontillo** [comment]
It does that [here](https://github.com/frakbot/FWeather/blob/develop/src/net/frakbot/FWeather/updater/UpdaterService.java#L255) by using a [WidgetHelper](https://github.com/frakbot/FWeather/blob/develop/src/net/frakbot/FWeather/util/WidgetHelper.java#L101) method.
