### ISSUE TITLE
Move to square/shuttle for translation

### ISSUE THREAD

**Issue by frapontillo** [frakbot/FWeather#78]
We can use [square/shuttle](https://github.com/square/shuttle) to provide translators a simple tool for translating strings. I will try to set up an instance, maybe on OpenShift.

**Comment by rock3r** [comment]
How's that coming along, @frapontillo ? I'd need to set things up for v2.2.

**Comment by frapontillo** [comment]
It's not. Moved to 3.0.

**Comment by rock3r** [comment]
You're a lazyass, dude.

**Comment by frapontillo** [comment]
Appreciate it. Back to SVD/LSI.

**Comment by frapontillo** [comment]
**Update**: requested a free account as an open source project on crowdin.net.
Closing for the moment.
