### ISSUE TITLE
Send feedback disabled

### ISSUE THREAD

**Issue by frapontillo** [frakbot/FWeather#84]
Tap on "send feedback". 
Dismiss the intent chooser. 
"send feedback " is disabled for good.

**Comment by rock3r** [comment]
Can't reproduce. Actually, the "send feedback" is re-enabled with a `postDelayed()`'d `Runnable`, after 5 seconds. This happens independently of the intent chooser, since that is provided by the OS and I have no control over its lifecycle, so I had to be creative :)

**Comment by frapontillo** [comment]
Yo.
