### ISSUE TITLE
Add a retry mechanism for the updates

### ISSUE THREAD

**Issue by rock3r** [frakbot/FWeather#87]
When the updates fail because of network issues, the widget should retry after a short wait for a certain number of times before giving up.

**Comment by rock3r** [comment]
This should further help working around issues #85 and #86

**Comment by rock3r** [comment]
I'd add: force closing and opening a **new** connection. This should fix any further issue with ECONNRESET.

**Comment by frapontillo** [comment]
This will include a cache overhaul: cache must expire.

**Comment by rock3r** [comment]
Cache expires after 2 hours. Or, at least, it's supposed to.

**Comment by frapontillo** [comment]
I have put the timeout to 1 ms and it keeps on getting the same information.

**Comment by rock3r** [comment]
That's strange, it used to work at one point. Who knows...

**Comment by frapontillo** [comment]
Can confirm it's working. I propose clearing the cache when the user explicitly requests an update by tapping on the refresh button. Agreed?

**Comment by rock3r** [comment]
Agreed!
