### ISSUE TITLE
Investigate possibile ART crashes on update

### ISSUE THREAD

**Issue by frapontillo** [frakbot/FWeather#89]
It's been reported that version 2.1.5 crashes after tapping on the refresh button.
Android VM is set to ART, though, so that may be worth investigating a little bit.

Device model: GT-I9305
Manifacturer: Samsung
Brand: samsung
CPU ABI: armeabi-v7a
Product: omni_i9305

Android version: REL
Release: 4.4
Incremental: eng.mark.20131116.073951
Build: samsung/omni_i9305/i9305:4.4/KRT16O/eng.mark.20131116.073951:userdebug/test-keys
Kernel: Linux version 3.0.64-CM-g7fc3ce7 (mark@mark-mint) (gcc version 4.7 (GCC) ) #6 SMP PREEMPT Sun Nov 17 21:34:12 EST 2013
App version: 2.1.5

**Comment by rock3r** [comment]
We're not going to debug the ART runtime. This is an unsupported runtime as far as I'm concerned, and people is **not** supposed to be using ART anyway.
